INSERT INTO chat_link(chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (1, 1)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (2, 1)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (3, 1)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (4, 1)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (5, 1)
ON CONFLICT DO NOTHING;
