INSERT INTO chat_link(id, chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (1, 10, 10)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(id, chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (2, 20, 10)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(id, chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (3, 30, 10)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(id, chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (4, 40, 10)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(id, chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (5, 50, 10)
ON CONFLICT DO NOTHING;
