INSERT INTO chat(id, tg_chat_id, created_at) OVERRIDING SYSTEM VALUE
VALUES (1, 1, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
INSERT INTO chat(id, tg_chat_id, created_at) OVERRIDING SYSTEM VALUE
VALUES (2, 2, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
INSERT INTO chat(id, tg_chat_id, created_at) OVERRIDING SYSTEM VALUE
VALUES (3, 3, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
INSERT INTO chat(id, tg_chat_id, created_at) OVERRIDING SYSTEM VALUE
VALUES (4, 4, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
INSERT INTO chat(id, tg_chat_id, created_at) OVERRIDING SYSTEM VALUE
VALUES (5, 5, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
