INSERT INTO chat_link(id, chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (1, 1, 1)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(id, chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (2, 2, 1)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(id, chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (3, 3, 1)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(id, chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (4, 4, 1)
ON CONFLICT DO NOTHING;
INSERT INTO chat_link(id, chat_id, link_id) OVERRIDING SYSTEM VALUE
VALUES (5, 5, 1)
ON CONFLICT DO NOTHING;
