INSERT INTO chat(id, tg_chat_id, created_at) OVERRIDING SYSTEM VALUE
VALUES (10, 1, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
INSERT INTO chat(id, tg_chat_id, created_at) OVERRIDING SYSTEM VALUE
VALUES (20, 2, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
INSERT INTO chat(id, tg_chat_id, created_at) OVERRIDING SYSTEM VALUE
VALUES (30, 3, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
INSERT INTO chat(id, tg_chat_id, created_at) OVERRIDING SYSTEM VALUE
VALUES (40, 4, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
INSERT INTO chat(id, tg_chat_id, created_at) OVERRIDING SYSTEM VALUE
VALUES (50, 5, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
