/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.generate;


import edu.java.scrapper.domain.jooq.generate.tables.Chat;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TG_CHAT_ID_INDEX = Internal.createIndex(DSL.name("TG_CHAT_ID_INDEX"), Chat.CHAT, new OrderField[] { Chat.CHAT.TG_CHAT_ID }, false);
}
