app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  api:
    git-url: https://api.github.com
    stackoverflow-url: https://api.stackexchange.com/2.3
    bot-url: http://localhost:8090
  supported:
    stackoverflow: stackoverflow.com
    github: github.com
  database-access-type: jpa

springdoc.swagger-ui.path: /swagger-ui.html

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
