app:
  telegram-token: ${TELEGRAM_API_TOKEN}
  api:
    scrapper-url: http://localhost:8080

supported:
  stackoverflow: stackoverflow.com
  github: github.com

springdoc.swagger-ui.path: /swagger-ui.html

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
