app:
  telegram-token: ${TELEGRAM_API_TOKEN}
  scrapper-url: http://localhost:8080

supported:
  domains:
    - stackoverflow.com
    - github.com

springdoc.swagger-ui.path: /swagger-ui.html

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
